"""
Author: Ajay Anand
"""


class YelpBusinessDataSchema:
    COL_BUSINESS_ID = "BusinessId"
    COL_RESTAURANT_NAME = "RestaurantName"
    COL_NEIGHBORHOOD = "Neighborhood"
    COL_ADDRESS = "Address"
    COL_CITY = "City"
    COL_STATE = "State"
    COL_ZIP = "Zip"
    COL_STARS = "Stars"
    COL_REVIEW_COUNT = "ReviewCount"
    COL_ACCEPTS_INSURANCE = "AcceptsInsurance"
    COL_AGES_ALLOWED = "AgesAllowed"
    COL_ALCOHOL = "Alcohol"
    COL_AMBIENCE = "Ambience" # have to check the type
    COL_BYOB = "BYOB"
    COL_BYOB_Corkage = "BYOBCorkage"
    COL_BEST_NIGHTS = "BestNights" # have to check the type
    COL_BIKE_PARKING = "BikeParking"
    COL_BUSINESS_ACCEPTS_BITCOIN = "BusinessAcceptsBitcoin"
    COL_BUSINESS_ACCEPTS_CREDITCARDS = "BusinessAcceptsCreditCards"
    COL_BUSINESS_PARKING = "BusinessParking" # have to check the type
    COL_BYAPPOINTMENTONLY = "ByAppointmentOnly"
    COL_CATERS = "Caters"
    COL_COAT_CHECK = "CoatCheck"
    COL_CORKAGE = "Corkage"
    COL_DIETARY_RESTRICTIONS = "DietaryRestrictions" # have to check the type
    COL_DOGS_ALLOWED = "DogsAllowed"
    COL_DRIVE_THRU = "DriveThru"
    COL_GOOD_FOR_DANCING = "GoodForDancing"
    COL_GOOD_FOR_KIDS = "GoodForKids"
    COL_GOOD_FOR_MEAL = "GoodForMeal" # have to check the type
    COL_HAIR_SPECIALIZES_IN = "HairSpecializesIn" # have to check the type
    COL_HAPPY_HOUR = "HappyHour"
    COL_HAS_TV = "HasTV"
    COL_MUSIC = "Music" # have to check the type
    COL_NOISE_LEVEL = "NoiseLevel"
    COL_OPEN_24_HOURS = "Open24Hours"
    COL_OUTDOOR_SEATING = "OutdoorSeating"
    COL_RESTAURANTS_ATTIRE = "RestaurantsAttire"
    COL_RESTAURANTS_COUNTER_SERVICE = "RestaurantsCounterService"
    COL_RESTAURANTS_DELIVERY = "RestaurantsDelivery"
    COL_RESTAURANTS_GOOD_FOR_GROUPS = "RestaurantsGoodForGroups"
    COL_RESTAURANTS_PRICE_RANGE2 = "RestaurantsPriceRange2"
    COL_RESTAURANTS_RESERVATIONS = "RestaurantsReservations"
    COL_RESTAURANTS_TABLE_SERVICE = "RestaurantsTableService"
    COL_RESTAURANTS_TAKEOUT = "RestaurantsTakeOut"
    COL_SMOKING = "Smoking"
    CoL_WHEELCHAIR_ACCESSIBLE = "WheelchairAccessible"
    COL_WIFI = "WiFi"


class LasVegasGovtDataSchema:
    COL_RESTAURANT_NAME = 'RestaurantName'
    COL_LOCATION_NAME = "LocationName"
    COL_CATEGORY_NAME = "CategoryName"
    COL_ADDRESS = "Address"
    COL_CITY = "City"
    COL_STATE = "State"
    COL_ZIP = 'Zip'
    COL_CURRENT_GRADE = "CurrentGrade"
    COL_INSPECTION_GRADE = "InspectionGrade"
    COL_VIOLATIONS = "Violations"
    COL_CURRENT_DEMERITS = "CurrentDemerits"
    COL_INSPECTION_DEMERITS = "InspectionDemerits"
    COL_CURRENT_SCORE = "CurrentScore"
    COL_INSPECTION_SCORE = "InspectionScore"


class LosAngelesGovtDataSchema:
    COL_ACTIVITY_DATE = "ACTIVITY DATE"
    COL_RECORD_ID = "RECORD ID"
    COL_NAME = "NAME"
    COL_ADDRESS = "ADDRESS"
    COL_SITE_ADDRESS = "SITE ADDRESS"
    COL_SITE_CITY = "SITE CITY"
    COL_SITE_STATE = "SITE STATE"
    COL_SITE_ZIP = "SITE ZIP"
    COL_PROGRAM_ELEMENT_CODE = "PROGRAM ELEMENT CODE"
    COL_PROGRAM_ELEMENT_CODE_DESCRIPTION = "PROGRAM ELEMENT CODE DESCRIPTION"
    COL_SERVICE_DESCRIPTION = "SERVICE DESCRIPTION"
    COL_ROW_ID = "ROW ID"
    COL_VIOLATION_CODE = "VIOLATION CODE"
    COL_VIOLATION_CODE_DESCRIPTION = "VIOLATION CODE DESCRIPTION"
    COl_POINTS = "POINTS"
    COl_SCORE = "SCORE"
    COL_GRADE = "GRADE"
    COl_COUNT = "COUNT"
    COl_RATING = "RATING"
    COL_REVIEW = "REVIEW"
    COl_PRICE = "PRICE"
    COl_PHONE = "PHONE"
    COl_TAKES_RESERVATIONS = "Takes Reservations"
    COl_DELIVERY = "Delivery"
    COl_TAKEOUT = "Take-out"
    COl_ACCEPT_CREDIT_CARD = "Accepts Credit Cards"
    COl_ACCEPT_APPLE_PAY = "Accepts Apple Pay"
    COl_GOOD_FOR = "Good For"
    COl_PARKING = "Parking"
    COl_BIKE_PARKING = "Bike Parking"
    COL_GOOD_FOR_KIDS = "Good for Kids"
    COL_GOOD_FOR_GROUPS = "Good for Groups"
    COL_ATTIRE = "Attire"
    COl_AMBIENCE = "Ambience"
    COl_NOISE_LEVEL = "Noise Level"
    COl_ALCOHOL = "Alcohol"
    COL_OUTDOOR_SEATING = "Outdoor Seating"
    COL_WIFI = "Wi-Fi"
    COL_HAS_TV = "Has TV"
    COL_CATERS = "Caters"
    COL_GOOD_FOR_WORKING = "Good for Working"
    COL_GENDER_NEUTRAL_RESTROOMS = "Gender Neutral Restrooms"